access_grant_max_days: 730
access_grant_min_days: 7
access_upfront_max_days: 180
api_root_path: /
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  name: null
auth_key: '{}'
auth_map_claims: {}
auto_reload: true
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
data_steward_email: helpdesk@ghga.de
db_connection_str: '**********'
db_name: dev-db
docs_url: /docs
download_access_url: http://127.0.0.1:8080/download-access
host: 127.0.0.1
kafka_servers:
- kafka:9092
log_level: info
notification_event_topic: notifications
notification_event_type: notification
openapi_url: /openapi.json
port: 8080
service_instance_id: '001'
service_name: ars
workers: 1
