api_root_path: /
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  name: null
auth_key: '{}'
auth_map_claims: {}
auto_reload: true
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
db_connection_str: '**********'
db_name: dev-db
docs_url: /docs
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
service_name: ars
workers: 1
