access_grant_max_days: 730
access_grant_min_days: 7
access_request_allowed_event_type: access_request_allowed
access_request_created_event_type: access_request_created
access_request_denied_event_type: access_request_denied
access_request_events_topic: access_request_events
access_upfront_max_days: 180
api_root_path: ''
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  id: null
  name: null
auth_key: '{}'
auth_map_claims: {}
auto_reload: true
cors_allow_credentials: false
cors_allowed_headers: []
cors_allowed_methods: []
cors_allowed_origins: []
db_connection_str: '**********'
db_name: access-requests
docs_url: /docs
download_access_url: http://127.0.0.1:8080/download-access
generate_correlation_id: true
host: 127.0.0.1
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
openapi_url: /openapi.json
port: 8080
service_instance_id: '1'
service_name: ars
workers: 1
