host: 127.0.0.1
port: 8080
log_level: INFO
workers: 1
auto_reload: true
cors_allowed_origins: []
cors_allow_credentials: False
cors_allowed_methods: []
cors_allowed_headers: []

db_connection_str: "mongodb://mongodb:27017"
db_name: "access-requests"

access_request_events_topic: access_request_events
access_request_created_type: access_request_created
access_request_allowed_type: access_request_allowed
access_request_denied_type: access_request_denied

service_instance_id: "1"
kafka_servers: ["kafka:9092"]

download_access_url: "http://127.0.0.1:8080/download-access"

data_steward_email: "helpdesk@ghga.de"

auth_key: "{}"
